scoreboard players set @s[scores={agility_level=2}] agility_xp_r 535
scoreboard players set @s[scores={agility_level=3}] agility_xp_r 548
scoreboard players set @s[scores={agility_level=4}] agility_xp_r 573
scoreboard players set @s[scores={agility_level=5}] agility_xp_r 600
scoreboard players set @s[scores={agility_level=6}] agility_xp_r 629
scoreboard players set @s[scores={agility_level=7}] agility_xp_r 661
scoreboard players set @s[scores={agility_level=8}] agility_xp_r 696
scoreboard players set @s[scores={agility_level=9}] agility_xp_r 735
scoreboard players set @s[scores={agility_level=10}] agility_xp_r 777
scoreboard players set @s[scores={agility_level=11}] agility_xp_r 825
scoreboard players set @s[scores={agility_level=12}] agility_xp_r 878
scoreboard players set @s[scores={agility_level=13}] agility_xp_r 936
scoreboard players set @s[scores={agility_level=14}] agility_xp_r 1001
scoreboard players set @s[scores={agility_level=15}] agility_xp_r 1073
scoreboard players set @s[scores={agility_level=16}] agility_xp_r 1152
scoreboard players set @s[scores={agility_level=17}] agility_xp_r 1238
scoreboard players set @s[scores={agility_level=18}] agility_xp_r 1334
scoreboard players set @s[scores={agility_level=19}] agility_xp_r 1438
scoreboard players set @s[scores={agility_level=20}] agility_xp_r 1552
scoreboard players set @s[scores={agility_level=21}] agility_xp_r 1675
scoreboard players set @s[scores={agility_level=22}] agility_xp_r 1809
scoreboard players set @s[scores={agility_level=23}] agility_xp_r 1954
scoreboard players set @s[scores={agility_level=24}] agility_xp_r 2111
scoreboard players set @s[scores={agility_level=25}] agility_xp_r 2280
scoreboard players set @s[scores={agility_level=26}] agility_xp_r 2461
scoreboard players set @s[scores={agility_level=27}] agility_xp_r 2656
scoreboard players set @s[scores={agility_level=28}] agility_xp_r 2864
scoreboard players set @s[scores={agility_level=29}] agility_xp_r 3086
scoreboard players set @s[scores={agility_level=30}] agility_xp_r 3323
scoreboard players set @s[scores={agility_level=31}] agility_xp_r 3575
scoreboard players set @s[scores={agility_level=32}] agility_xp_r 3843
scoreboard players set @s[scores={agility_level=33}] agility_xp_r 4128
scoreboard players set @s[scores={agility_level=34}] agility_xp_r 4429
scoreboard players set @s[scores={agility_level=35}] agility_xp_r 4747
scoreboard players set @s[scores={agility_level=36}] agility_xp_r 5083
scoreboard players set @s[scores={agility_level=37}] agility_xp_r 5438
scoreboard players set @s[scores={agility_level=38}] agility_xp_r 5812
scoreboard players set @s[scores={agility_level=39}] agility_xp_r 6205
scoreboard players set @s[scores={agility_level=40}] agility_xp_r 6617
scoreboard players set @s[scores={agility_level=41}] agility_xp_r 7051
scoreboard players set @s[scores={agility_level=42}] agility_xp_r 7505
scoreboard players set @s[scores={agility_level=43}] agility_xp_r 7981
scoreboard players set @s[scores={agility_level=44}] agility_xp_r 8479
scoreboard players set @s[scores={agility_level=45}] agility_xp_r 9000
scoreboard players set @s[scores={agility_level=46}] agility_xp_r 9543
scoreboard players set @s[scores={agility_level=47}] agility_xp_r 10110
scoreboard players set @s[scores={agility_level=48}] agility_xp_r 10702
scoreboard players set @s[scores={agility_level=49}] agility_xp_r 11318
scoreboard players set @s[scores={agility_level=50}] agility_xp_r 11959
scoreboard players set @s[scores={agility_level=51}] agility_xp_r 12626
scoreboard players set @s[scores={agility_level=52}] agility_xp_r 13319
scoreboard players set @s[scores={agility_level=53}] agility_xp_r 14039
scoreboard players set @s[scores={agility_level=54}] agility_xp_r 14787
scoreboard players set @s[scores={agility_level=55}] agility_xp_r 15562
scoreboard players set @s[scores={agility_level=56}] agility_xp_r 16365
scoreboard players set @s[scores={agility_level=57}] agility_xp_r 17198
scoreboard players set @s[scores={agility_level=58}] agility_xp_r 18060
scoreboard players set @s[scores={agility_level=59}] agility_xp_r 18951
scoreboard players set @s[scores={agility_level=60}] agility_xp_r 19873
scoreboard players set @s[scores={agility_level=61}] agility_xp_r 20826
scoreboard players set @s[scores={agility_level=62}] agility_xp_r 21811
scoreboard players set @s[scores={agility_level=63}] agility_xp_r 22828
scoreboard players set @s[scores={agility_level=64}] agility_xp_r 23877
scoreboard players set @s[scores={agility_level=65}] agility_xp_r 24959
scoreboard players set @s[scores={agility_level=66}] agility_xp_r 26075
scoreboard players set @s[scores={agility_level=67}] agility_xp_r 27255
scoreboard players set @s[scores={agility_level=68}] agility_xp_r 28410
scoreboard players set @s[scores={agility_level=69}] agility_xp_r 29630
scoreboard players set @s[scores={agility_level=70}] agility_xp_r 30885
scoreboard players set @s[scores={agility_level=71}] agility_xp_r 32177
scoreboard players set @s[scores={agility_level=72}] agility_xp_r 33505
scoreboard players set @s[scores={agility_level=73}] agility_xp_r 34871
scoreboard players set @s[scores={agility_level=74}] agility_xp_r 36275
scoreboard players set @s[scores={agility_level=75}] agility_xp_r 37717
scoreboard players set @s[scores={agility_level=76}] agility_xp_r 39197
scoreboard players set @s[scores={agility_level=77}] agility_xp_r 40717
scoreboard players set @s[scores={agility_level=78}] agility_xp_r 42277
scoreboard players set @s[scores={agility_level=79}] agility_xp_r 43878
scoreboard players set @s[scores={agility_level=80}] agility_xp_r 45519
scoreboard players set @s[scores={agility_level=81}] agility_xp_r 47202
scoreboard players set @s[scores={agility_level=82}] agility_xp_r 48927
scoreboard players set @s[scores={agility_level=83}] agility_xp_r 50694
scoreboard players set @s[scores={agility_level=84}] agility_xp_r 52505
scoreboard players set @s[scores={agility_level=85}] agility_xp_r 54359
scoreboard players set @s[scores={agility_level=86}] agility_xp_r 56257
scoreboard players set @s[scores={agility_level=87}] agility_xp_r 58200
scoreboard players set @s[scores={agility_level=88}] agility_xp_r 60188
scoreboard players set @s[scores={agility_level=89}] agility_xp_r 62221
scoreboard players set @s[scores={agility_level=90}] agility_xp_r 64301
scoreboard players set @s[scores={agility_level=91}] agility_xp_r 66427
scoreboard players set @s[scores={agility_level=92}] agility_xp_r 68601
scoreboard players set @s[scores={agility_level=93}] agility_xp_r 70823
scoreboard players set @s[scores={agility_level=94}] agility_xp_r 73093
scoreboard players set @s[scores={agility_level=95}] agility_xp_r 75411
scoreboard players set @s[scores={agility_level=96}] agility_xp_r 77779
scoreboard players set @s[scores={agility_level=97}] agility_xp_r 80197
scoreboard players set @s[scores={agility_level=98}] agility_xp_r 82665
scoreboard players set @s[scores={agility_level=99}] agility_xp_r 85185
scoreboard players set @s[scores={agility_level=100}] agility_xp_r 87755
scoreboard players set @s[scores={agility_level=101}] agility_xp_r 90378
scoreboard players set @s[scores={agility_level=102}] agility_xp_r 93053
scoreboard players set @s[scores={agility_level=103}] agility_xp_r 95781
scoreboard players set @s[scores={agility_level=104}] agility_xp_r 98563
scoreboard players set @s[scores={agility_level=105}] agility_xp_r 101399
scoreboard players set @s[scores={agility_level=106}] agility_xp_r 104289
scoreboard players set @s[scores={agility_level=107}] agility_xp_r 107234
scoreboard players set @s[scores={agility_level=108}] agility_xp_r 110236
scoreboard players set @s[scores={agility_level=109}] agility_xp_r 113293
scoreboard players set @s[scores={agility_level=110}] agility_xp_r 116407
scoreboard players set @s[scores={agility_level=111}] agility_xp_r 119578
scoreboard players set @s[scores={agility_level=112}] agility_xp_r 122807
scoreboard players set @s[scores={agility_level=113}] agility_xp_r 126094
scoreboard players set @s[scores={agility_level=114}] agility_xp_r 129441
scoreboard players set @s[scores={agility_level=115}] agility_xp_r 132846
scoreboard players set @s[scores={agility_level=116}] agility_xp_r 136311
scoreboard players set @s[scores={agility_level=117}] agility_xp_r 139837
scoreboard players set @s[scores={agility_level=118}] agility_xp_r 143423
scoreboard players set @s[scores={agility_level=119}] agility_xp_r 147071