scoreboard players set @s[scores={attack_level=2}] attack_xp_r 535
scoreboard players set @s[scores={attack_level=3}] attack_xp_r 548
scoreboard players set @s[scores={attack_level=4}] attack_xp_r 573
scoreboard players set @s[scores={attack_level=5}] attack_xp_r 600
scoreboard players set @s[scores={attack_level=6}] attack_xp_r 629
scoreboard players set @s[scores={attack_level=7}] attack_xp_r 661
scoreboard players set @s[scores={attack_level=8}] attack_xp_r 696
scoreboard players set @s[scores={attack_level=9}] attack_xp_r 735
scoreboard players set @s[scores={attack_level=10}] attack_xp_r 777
scoreboard players set @s[scores={attack_level=11}] attack_xp_r 825
scoreboard players set @s[scores={attack_level=12}] attack_xp_r 878
scoreboard players set @s[scores={attack_level=13}] attack_xp_r 936
scoreboard players set @s[scores={attack_level=14}] attack_xp_r 1001
scoreboard players set @s[scores={attack_level=15}] attack_xp_r 1073
scoreboard players set @s[scores={attack_level=16}] attack_xp_r 1152
scoreboard players set @s[scores={attack_level=17}] attack_xp_r 1238
scoreboard players set @s[scores={attack_level=18}] attack_xp_r 1334
scoreboard players set @s[scores={attack_level=19}] attack_xp_r 1438
scoreboard players set @s[scores={attack_level=20}] attack_xp_r 1552
scoreboard players set @s[scores={attack_level=21}] attack_xp_r 1675
scoreboard players set @s[scores={attack_level=22}] attack_xp_r 1809
scoreboard players set @s[scores={attack_level=23}] attack_xp_r 1954
scoreboard players set @s[scores={attack_level=24}] attack_xp_r 2111
scoreboard players set @s[scores={attack_level=25}] attack_xp_r 2280
scoreboard players set @s[scores={attack_level=26}] attack_xp_r 2461
scoreboard players set @s[scores={attack_level=27}] attack_xp_r 2656
scoreboard players set @s[scores={attack_level=28}] attack_xp_r 2864
scoreboard players set @s[scores={attack_level=29}] attack_xp_r 3086
scoreboard players set @s[scores={attack_level=30}] attack_xp_r 3323
scoreboard players set @s[scores={attack_level=31}] attack_xp_r 3575
scoreboard players set @s[scores={attack_level=32}] attack_xp_r 3843
scoreboard players set @s[scores={attack_level=33}] attack_xp_r 4128
scoreboard players set @s[scores={attack_level=34}] attack_xp_r 4429
scoreboard players set @s[scores={attack_level=35}] attack_xp_r 4747
scoreboard players set @s[scores={attack_level=36}] attack_xp_r 5083
scoreboard players set @s[scores={attack_level=37}] attack_xp_r 5438
scoreboard players set @s[scores={attack_level=38}] attack_xp_r 5812
scoreboard players set @s[scores={attack_level=39}] attack_xp_r 6205
scoreboard players set @s[scores={attack_level=40}] attack_xp_r 6617
scoreboard players set @s[scores={attack_level=41}] attack_xp_r 7051
scoreboard players set @s[scores={attack_level=42}] attack_xp_r 7505
scoreboard players set @s[scores={attack_level=43}] attack_xp_r 7981
scoreboard players set @s[scores={attack_level=44}] attack_xp_r 8479
scoreboard players set @s[scores={attack_level=45}] attack_xp_r 9000
scoreboard players set @s[scores={attack_level=46}] attack_xp_r 9543
scoreboard players set @s[scores={attack_level=47}] attack_xp_r 10110
scoreboard players set @s[scores={attack_level=48}] attack_xp_r 10702
scoreboard players set @s[scores={attack_level=49}] attack_xp_r 11318
scoreboard players set @s[scores={attack_level=50}] attack_xp_r 11959
scoreboard players set @s[scores={attack_level=51}] attack_xp_r 12626
scoreboard players set @s[scores={attack_level=52}] attack_xp_r 13319
scoreboard players set @s[scores={attack_level=53}] attack_xp_r 14039
scoreboard players set @s[scores={attack_level=54}] attack_xp_r 14787
scoreboard players set @s[scores={attack_level=55}] attack_xp_r 15562
scoreboard players set @s[scores={attack_level=56}] attack_xp_r 16365
scoreboard players set @s[scores={attack_level=57}] attack_xp_r 17198
scoreboard players set @s[scores={attack_level=58}] attack_xp_r 18060
scoreboard players set @s[scores={attack_level=59}] attack_xp_r 18951
scoreboard players set @s[scores={attack_level=60}] attack_xp_r 19873
scoreboard players set @s[scores={attack_level=61}] attack_xp_r 20826
scoreboard players set @s[scores={attack_level=62}] attack_xp_r 21811
scoreboard players set @s[scores={attack_level=63}] attack_xp_r 22828
scoreboard players set @s[scores={attack_level=64}] attack_xp_r 23877
scoreboard players set @s[scores={attack_level=65}] attack_xp_r 24959
scoreboard players set @s[scores={attack_level=66}] attack_xp_r 26075
scoreboard players set @s[scores={attack_level=67}] attack_xp_r 27255
scoreboard players set @s[scores={attack_level=68}] attack_xp_r 28410
scoreboard players set @s[scores={attack_level=69}] attack_xp_r 29630
scoreboard players set @s[scores={attack_level=70}] attack_xp_r 30885
scoreboard players set @s[scores={attack_level=71}] attack_xp_r 32177
scoreboard players set @s[scores={attack_level=72}] attack_xp_r 33505
scoreboard players set @s[scores={attack_level=73}] attack_xp_r 34871
scoreboard players set @s[scores={attack_level=74}] attack_xp_r 36275
scoreboard players set @s[scores={attack_level=75}] attack_xp_r 37717
scoreboard players set @s[scores={attack_level=76}] attack_xp_r 39197
scoreboard players set @s[scores={attack_level=77}] attack_xp_r 40717
scoreboard players set @s[scores={attack_level=78}] attack_xp_r 42277
scoreboard players set @s[scores={attack_level=79}] attack_xp_r 43878
scoreboard players set @s[scores={attack_level=80}] attack_xp_r 45519
scoreboard players set @s[scores={attack_level=81}] attack_xp_r 47202
scoreboard players set @s[scores={attack_level=82}] attack_xp_r 48927
scoreboard players set @s[scores={attack_level=83}] attack_xp_r 50694
scoreboard players set @s[scores={attack_level=84}] attack_xp_r 52505
scoreboard players set @s[scores={attack_level=85}] attack_xp_r 54359
scoreboard players set @s[scores={attack_level=86}] attack_xp_r 56257
scoreboard players set @s[scores={attack_level=87}] attack_xp_r 58200
scoreboard players set @s[scores={attack_level=88}] attack_xp_r 60188
scoreboard players set @s[scores={attack_level=89}] attack_xp_r 62221
scoreboard players set @s[scores={attack_level=90}] attack_xp_r 64301
scoreboard players set @s[scores={attack_level=91}] attack_xp_r 66427
scoreboard players set @s[scores={attack_level=92}] attack_xp_r 68601
scoreboard players set @s[scores={attack_level=93}] attack_xp_r 70823
scoreboard players set @s[scores={attack_level=94}] attack_xp_r 73093
scoreboard players set @s[scores={attack_level=95}] attack_xp_r 75411
scoreboard players set @s[scores={attack_level=96}] attack_xp_r 77779
scoreboard players set @s[scores={attack_level=97}] attack_xp_r 80197
scoreboard players set @s[scores={attack_level=98}] attack_xp_r 82665
scoreboard players set @s[scores={attack_level=99}] attack_xp_r 85185
scoreboard players set @s[scores={attack_level=100}] attack_xp_r 87755
scoreboard players set @s[scores={attack_level=101}] attack_xp_r 90378
scoreboard players set @s[scores={attack_level=102}] attack_xp_r 93053
scoreboard players set @s[scores={attack_level=103}] attack_xp_r 95781
scoreboard players set @s[scores={attack_level=104}] attack_xp_r 98563
scoreboard players set @s[scores={attack_level=105}] attack_xp_r 101399
scoreboard players set @s[scores={attack_level=106}] attack_xp_r 104289
scoreboard players set @s[scores={attack_level=107}] attack_xp_r 107234
scoreboard players set @s[scores={attack_level=108}] attack_xp_r 110236
scoreboard players set @s[scores={attack_level=109}] attack_xp_r 113293
scoreboard players set @s[scores={attack_level=110}] attack_xp_r 116407
scoreboard players set @s[scores={attack_level=111}] attack_xp_r 119578
scoreboard players set @s[scores={attack_level=112}] attack_xp_r 122807
scoreboard players set @s[scores={attack_level=113}] attack_xp_r 126094
scoreboard players set @s[scores={attack_level=114}] attack_xp_r 129441
scoreboard players set @s[scores={attack_level=115}] attack_xp_r 132846
scoreboard players set @s[scores={attack_level=116}] attack_xp_r 136311
scoreboard players set @s[scores={attack_level=117}] attack_xp_r 139837
scoreboard players set @s[scores={attack_level=118}] attack_xp_r 143423
scoreboard players set @s[scores={attack_level=119}] attack_xp_r 147071