scoreboard players set @s[scores={const_level=2}] const_xp_r 535
scoreboard players set @s[scores={const_level=3}] const_xp_r 548
scoreboard players set @s[scores={const_level=4}] const_xp_r 573
scoreboard players set @s[scores={const_level=5}] const_xp_r 600
scoreboard players set @s[scores={const_level=6}] const_xp_r 629
scoreboard players set @s[scores={const_level=7}] const_xp_r 661
scoreboard players set @s[scores={const_level=8}] const_xp_r 696
scoreboard players set @s[scores={const_level=9}] const_xp_r 735
scoreboard players set @s[scores={const_level=10}] const_xp_r 777
scoreboard players set @s[scores={const_level=11}] const_xp_r 825
scoreboard players set @s[scores={const_level=12}] const_xp_r 878
scoreboard players set @s[scores={const_level=13}] const_xp_r 936
scoreboard players set @s[scores={const_level=14}] const_xp_r 1001
scoreboard players set @s[scores={const_level=15}] const_xp_r 1073
scoreboard players set @s[scores={const_level=16}] const_xp_r 1152
scoreboard players set @s[scores={const_level=17}] const_xp_r 1238
scoreboard players set @s[scores={const_level=18}] const_xp_r 1334
scoreboard players set @s[scores={const_level=19}] const_xp_r 1438
scoreboard players set @s[scores={const_level=20}] const_xp_r 1552
scoreboard players set @s[scores={const_level=21}] const_xp_r 1675
scoreboard players set @s[scores={const_level=22}] const_xp_r 1809
scoreboard players set @s[scores={const_level=23}] const_xp_r 1954
scoreboard players set @s[scores={const_level=24}] const_xp_r 2111
scoreboard players set @s[scores={const_level=25}] const_xp_r 2280
scoreboard players set @s[scores={const_level=26}] const_xp_r 2461
scoreboard players set @s[scores={const_level=27}] const_xp_r 2656
scoreboard players set @s[scores={const_level=28}] const_xp_r 2864
scoreboard players set @s[scores={const_level=29}] const_xp_r 3086
scoreboard players set @s[scores={const_level=30}] const_xp_r 3323
scoreboard players set @s[scores={const_level=31}] const_xp_r 3575
scoreboard players set @s[scores={const_level=32}] const_xp_r 3843
scoreboard players set @s[scores={const_level=33}] const_xp_r 4128
scoreboard players set @s[scores={const_level=34}] const_xp_r 4429
scoreboard players set @s[scores={const_level=35}] const_xp_r 4747
scoreboard players set @s[scores={const_level=36}] const_xp_r 5083
scoreboard players set @s[scores={const_level=37}] const_xp_r 5438
scoreboard players set @s[scores={const_level=38}] const_xp_r 5812
scoreboard players set @s[scores={const_level=39}] const_xp_r 6205
scoreboard players set @s[scores={const_level=40}] const_xp_r 6617
scoreboard players set @s[scores={const_level=41}] const_xp_r 7051
scoreboard players set @s[scores={const_level=42}] const_xp_r 7505
scoreboard players set @s[scores={const_level=43}] const_xp_r 7981
scoreboard players set @s[scores={const_level=44}] const_xp_r 8479
scoreboard players set @s[scores={const_level=45}] const_xp_r 9000
scoreboard players set @s[scores={const_level=46}] const_xp_r 9543
scoreboard players set @s[scores={const_level=47}] const_xp_r 10110
scoreboard players set @s[scores={const_level=48}] const_xp_r 10702
scoreboard players set @s[scores={const_level=49}] const_xp_r 11318
scoreboard players set @s[scores={const_level=50}] const_xp_r 11959
scoreboard players set @s[scores={const_level=51}] const_xp_r 12626
scoreboard players set @s[scores={const_level=52}] const_xp_r 13319
scoreboard players set @s[scores={const_level=53}] const_xp_r 14039
scoreboard players set @s[scores={const_level=54}] const_xp_r 14787
scoreboard players set @s[scores={const_level=55}] const_xp_r 15562
scoreboard players set @s[scores={const_level=56}] const_xp_r 16365
scoreboard players set @s[scores={const_level=57}] const_xp_r 17198
scoreboard players set @s[scores={const_level=58}] const_xp_r 18060
scoreboard players set @s[scores={const_level=59}] const_xp_r 18951
scoreboard players set @s[scores={const_level=60}] const_xp_r 19873
scoreboard players set @s[scores={const_level=61}] const_xp_r 20826
scoreboard players set @s[scores={const_level=62}] const_xp_r 21811
scoreboard players set @s[scores={const_level=63}] const_xp_r 22828
scoreboard players set @s[scores={const_level=64}] const_xp_r 23877
scoreboard players set @s[scores={const_level=65}] const_xp_r 24959
scoreboard players set @s[scores={const_level=66}] const_xp_r 26075
scoreboard players set @s[scores={const_level=67}] const_xp_r 27255
scoreboard players set @s[scores={const_level=68}] const_xp_r 28410
scoreboard players set @s[scores={const_level=69}] const_xp_r 29630
scoreboard players set @s[scores={const_level=70}] const_xp_r 30885
scoreboard players set @s[scores={const_level=71}] const_xp_r 32177
scoreboard players set @s[scores={const_level=72}] const_xp_r 33505
scoreboard players set @s[scores={const_level=73}] const_xp_r 34871
scoreboard players set @s[scores={const_level=74}] const_xp_r 36275
scoreboard players set @s[scores={const_level=75}] const_xp_r 37717
scoreboard players set @s[scores={const_level=76}] const_xp_r 39197
scoreboard players set @s[scores={const_level=77}] const_xp_r 40717
scoreboard players set @s[scores={const_level=78}] const_xp_r 42277
scoreboard players set @s[scores={const_level=79}] const_xp_r 43878
scoreboard players set @s[scores={const_level=80}] const_xp_r 45519
scoreboard players set @s[scores={const_level=81}] const_xp_r 47202
scoreboard players set @s[scores={const_level=82}] const_xp_r 48927
scoreboard players set @s[scores={const_level=83}] const_xp_r 50694
scoreboard players set @s[scores={const_level=84}] const_xp_r 52505
scoreboard players set @s[scores={const_level=85}] const_xp_r 54359
scoreboard players set @s[scores={const_level=86}] const_xp_r 56257
scoreboard players set @s[scores={const_level=87}] const_xp_r 58200
scoreboard players set @s[scores={const_level=88}] const_xp_r 60188
scoreboard players set @s[scores={const_level=89}] const_xp_r 62221
scoreboard players set @s[scores={const_level=90}] const_xp_r 64301
scoreboard players set @s[scores={const_level=91}] const_xp_r 66427
scoreboard players set @s[scores={const_level=92}] const_xp_r 68601
scoreboard players set @s[scores={const_level=93}] const_xp_r 70823
scoreboard players set @s[scores={const_level=94}] const_xp_r 73093
scoreboard players set @s[scores={const_level=95}] const_xp_r 75411
scoreboard players set @s[scores={const_level=96}] const_xp_r 77779
scoreboard players set @s[scores={const_level=97}] const_xp_r 80197
scoreboard players set @s[scores={const_level=98}] const_xp_r 82665
scoreboard players set @s[scores={const_level=99}] const_xp_r 85185
scoreboard players set @s[scores={const_level=100}] const_xp_r 87755
scoreboard players set @s[scores={const_level=101}] const_xp_r 90378
scoreboard players set @s[scores={const_level=102}] const_xp_r 93053
scoreboard players set @s[scores={const_level=103}] const_xp_r 95781
scoreboard players set @s[scores={const_level=104}] const_xp_r 98563
scoreboard players set @s[scores={const_level=105}] const_xp_r 101399
scoreboard players set @s[scores={const_level=106}] const_xp_r 104289
scoreboard players set @s[scores={const_level=107}] const_xp_r 107234
scoreboard players set @s[scores={const_level=108}] const_xp_r 110236
scoreboard players set @s[scores={const_level=109}] const_xp_r 113293
scoreboard players set @s[scores={const_level=110}] const_xp_r 116407
scoreboard players set @s[scores={const_level=111}] const_xp_r 119578
scoreboard players set @s[scores={const_level=112}] const_xp_r 122807
scoreboard players set @s[scores={const_level=113}] const_xp_r 126094
scoreboard players set @s[scores={const_level=114}] const_xp_r 129441
scoreboard players set @s[scores={const_level=115}] const_xp_r 132846
scoreboard players set @s[scores={const_level=116}] const_xp_r 136311
scoreboard players set @s[scores={const_level=117}] const_xp_r 139837
scoreboard players set @s[scores={const_level=118}] const_xp_r 143423
scoreboard players set @s[scores={const_level=119}] const_xp_r 147071