scoreboard players set @s[scores={defense_level=2}] def_xp_r 535
scoreboard players set @s[scores={defense_level=3}] def_xp_r 548
scoreboard players set @s[scores={defense_level=4}] def_xp_r 573
scoreboard players set @s[scores={defense_level=5}] def_xp_r 600
scoreboard players set @s[scores={defense_level=6}] def_xp_r 629
scoreboard players set @s[scores={defense_level=7}] def_xp_r 661
scoreboard players set @s[scores={defense_level=8}] def_xp_r 696
scoreboard players set @s[scores={defense_level=9}] def_xp_r 735
scoreboard players set @s[scores={defense_level=10}] def_xp_r 777
scoreboard players set @s[scores={defense_level=11}] def_xp_r 825
scoreboard players set @s[scores={defense_level=12}] def_xp_r 878
scoreboard players set @s[scores={defense_level=13}] def_xp_r 936
scoreboard players set @s[scores={defense_level=14}] def_xp_r 1001
scoreboard players set @s[scores={defense_level=15}] def_xp_r 1073
scoreboard players set @s[scores={defense_level=16}] def_xp_r 1152
scoreboard players set @s[scores={defense_level=17}] def_xp_r 1238
scoreboard players set @s[scores={defense_level=18}] def_xp_r 1334
scoreboard players set @s[scores={defense_level=19}] def_xp_r 1438
scoreboard players set @s[scores={defense_level=20}] def_xp_r 1552
scoreboard players set @s[scores={defense_level=21}] def_xp_r 1675
scoreboard players set @s[scores={defense_level=22}] def_xp_r 1809
scoreboard players set @s[scores={defense_level=23}] def_xp_r 1954
scoreboard players set @s[scores={defense_level=24}] def_xp_r 2111
scoreboard players set @s[scores={defense_level=25}] def_xp_r 2280
scoreboard players set @s[scores={defense_level=26}] def_xp_r 2461
scoreboard players set @s[scores={defense_level=27}] def_xp_r 2656
scoreboard players set @s[scores={defense_level=28}] def_xp_r 2864
scoreboard players set @s[scores={defense_level=29}] def_xp_r 3086
scoreboard players set @s[scores={defense_level=30}] def_xp_r 3323
scoreboard players set @s[scores={defense_level=31}] def_xp_r 3575
scoreboard players set @s[scores={defense_level=32}] def_xp_r 3843
scoreboard players set @s[scores={defense_level=33}] def_xp_r 4128
scoreboard players set @s[scores={defense_level=34}] def_xp_r 4429
scoreboard players set @s[scores={defense_level=35}] def_xp_r 4747
scoreboard players set @s[scores={defense_level=36}] def_xp_r 5083
scoreboard players set @s[scores={defense_level=37}] def_xp_r 5438
scoreboard players set @s[scores={defense_level=38}] def_xp_r 5812
scoreboard players set @s[scores={defense_level=39}] def_xp_r 6205
scoreboard players set @s[scores={defense_level=40}] def_xp_r 6617
scoreboard players set @s[scores={defense_level=41}] def_xp_r 7051
scoreboard players set @s[scores={defense_level=42}] def_xp_r 7505
scoreboard players set @s[scores={defense_level=43}] def_xp_r 7981
scoreboard players set @s[scores={defense_level=44}] def_xp_r 8479
scoreboard players set @s[scores={defense_level=45}] def_xp_r 9000
scoreboard players set @s[scores={defense_level=46}] def_xp_r 9543
scoreboard players set @s[scores={defense_level=47}] def_xp_r 10110
scoreboard players set @s[scores={defense_level=48}] def_xp_r 10702
scoreboard players set @s[scores={defense_level=49}] def_xp_r 11318
scoreboard players set @s[scores={defense_level=50}] def_xp_r 11959
scoreboard players set @s[scores={defense_level=51}] def_xp_r 12626
scoreboard players set @s[scores={defense_level=52}] def_xp_r 13319
scoreboard players set @s[scores={defense_level=53}] def_xp_r 14039
scoreboard players set @s[scores={defense_level=54}] def_xp_r 14787
scoreboard players set @s[scores={defense_level=55}] def_xp_r 15562
scoreboard players set @s[scores={defense_level=56}] def_xp_r 16365
scoreboard players set @s[scores={defense_level=57}] def_xp_r 17198
scoreboard players set @s[scores={defense_level=58}] def_xp_r 18060
scoreboard players set @s[scores={defense_level=59}] def_xp_r 18951
scoreboard players set @s[scores={defense_level=60}] def_xp_r 19873
scoreboard players set @s[scores={defense_level=61}] def_xp_r 20826
scoreboard players set @s[scores={defense_level=62}] def_xp_r 21811
scoreboard players set @s[scores={defense_level=63}] def_xp_r 22828
scoreboard players set @s[scores={defense_level=64}] def_xp_r 23877
scoreboard players set @s[scores={defense_level=65}] def_xp_r 24959
scoreboard players set @s[scores={defense_level=66}] def_xp_r 26075
scoreboard players set @s[scores={defense_level=67}] def_xp_r 27255
scoreboard players set @s[scores={defense_level=68}] def_xp_r 28410
scoreboard players set @s[scores={defense_level=69}] def_xp_r 29630
scoreboard players set @s[scores={defense_level=70}] def_xp_r 30885
scoreboard players set @s[scores={defense_level=71}] def_xp_r 32177
scoreboard players set @s[scores={defense_level=72}] def_xp_r 33505
scoreboard players set @s[scores={defense_level=73}] def_xp_r 34871
scoreboard players set @s[scores={defense_level=74}] def_xp_r 36275
scoreboard players set @s[scores={defense_level=75}] def_xp_r 37717
scoreboard players set @s[scores={defense_level=76}] def_xp_r 39197
scoreboard players set @s[scores={defense_level=77}] def_xp_r 40717
scoreboard players set @s[scores={defense_level=78}] def_xp_r 42277
scoreboard players set @s[scores={defense_level=79}] def_xp_r 43878
scoreboard players set @s[scores={defense_level=80}] def_xp_r 45519
scoreboard players set @s[scores={defense_level=81}] def_xp_r 47202
scoreboard players set @s[scores={defense_level=82}] def_xp_r 48927
scoreboard players set @s[scores={defense_level=83}] def_xp_r 50694
scoreboard players set @s[scores={defense_level=84}] def_xp_r 52505
scoreboard players set @s[scores={defense_level=85}] def_xp_r 54359
scoreboard players set @s[scores={defense_level=86}] def_xp_r 56257
scoreboard players set @s[scores={defense_level=87}] def_xp_r 58200
scoreboard players set @s[scores={defense_level=88}] def_xp_r 60188
scoreboard players set @s[scores={defense_level=89}] def_xp_r 62221
scoreboard players set @s[scores={defense_level=90}] def_xp_r 64301
scoreboard players set @s[scores={defense_level=91}] def_xp_r 66427
scoreboard players set @s[scores={defense_level=92}] def_xp_r 68601
scoreboard players set @s[scores={defense_level=93}] def_xp_r 70823
scoreboard players set @s[scores={defense_level=94}] def_xp_r 73093
scoreboard players set @s[scores={defense_level=95}] def_xp_r 75411
scoreboard players set @s[scores={defense_level=96}] def_xp_r 77779
scoreboard players set @s[scores={defense_level=97}] def_xp_r 80197
scoreboard players set @s[scores={defense_level=98}] def_xp_r 82665
scoreboard players set @s[scores={defense_level=99}] def_xp_r 85185
scoreboard players set @s[scores={defense_level=100}] def_xp_r 87755
scoreboard players set @s[scores={defense_level=101}] def_xp_r 90378
scoreboard players set @s[scores={defense_level=102}] def_xp_r 93053
scoreboard players set @s[scores={defense_level=103}] def_xp_r 95781
scoreboard players set @s[scores={defense_level=104}] def_xp_r 98563
scoreboard players set @s[scores={defense_level=105}] def_xp_r 101399
scoreboard players set @s[scores={defense_level=106}] def_xp_r 104289
scoreboard players set @s[scores={defense_level=107}] def_xp_r 107234
scoreboard players set @s[scores={defense_level=108}] def_xp_r 110236
scoreboard players set @s[scores={defense_level=109}] def_xp_r 113293
scoreboard players set @s[scores={defense_level=110}] def_xp_r 116407
scoreboard players set @s[scores={defense_level=111}] def_xp_r 119578
scoreboard players set @s[scores={defense_level=112}] def_xp_r 122807
scoreboard players set @s[scores={defense_level=113}] def_xp_r 126094
scoreboard players set @s[scores={defense_level=114}] def_xp_r 129441
scoreboard players set @s[scores={defense_level=115}] def_xp_r 132846
scoreboard players set @s[scores={defense_level=116}] def_xp_r 136311
scoreboard players set @s[scores={defense_level=117}] def_xp_r 139837
scoreboard players set @s[scores={defense_level=118}] def_xp_r 143423
scoreboard players set @s[scores={defense_level=119}] def_xp_r 147071