scoreboard players set @s[scores={ranged_level=2}] ranged_xp_r 535
scoreboard players set @s[scores={ranged_level=3}] ranged_xp_r 548
scoreboard players set @s[scores={ranged_level=4}] ranged_xp_r 573
scoreboard players set @s[scores={ranged_level=5}] ranged_xp_r 600
scoreboard players set @s[scores={ranged_level=6}] ranged_xp_r 629
scoreboard players set @s[scores={ranged_level=7}] ranged_xp_r 661
scoreboard players set @s[scores={ranged_level=8}] ranged_xp_r 696
scoreboard players set @s[scores={ranged_level=9}] ranged_xp_r 735
scoreboard players set @s[scores={ranged_level=10}] ranged_xp_r 777
scoreboard players set @s[scores={ranged_level=11}] ranged_xp_r 825
scoreboard players set @s[scores={ranged_level=12}] ranged_xp_r 878
scoreboard players set @s[scores={ranged_level=13}] ranged_xp_r 936
scoreboard players set @s[scores={ranged_level=14}] ranged_xp_r 1001
scoreboard players set @s[scores={ranged_level=15}] ranged_xp_r 1073
scoreboard players set @s[scores={ranged_level=16}] ranged_xp_r 1152
scoreboard players set @s[scores={ranged_level=17}] ranged_xp_r 1238
scoreboard players set @s[scores={ranged_level=18}] ranged_xp_r 1334
scoreboard players set @s[scores={ranged_level=19}] ranged_xp_r 1438
scoreboard players set @s[scores={ranged_level=20}] ranged_xp_r 1552
scoreboard players set @s[scores={ranged_level=21}] ranged_xp_r 1675
scoreboard players set @s[scores={ranged_level=22}] ranged_xp_r 1809
scoreboard players set @s[scores={ranged_level=23}] ranged_xp_r 1954
scoreboard players set @s[scores={ranged_level=24}] ranged_xp_r 2111
scoreboard players set @s[scores={ranged_level=25}] ranged_xp_r 2280
scoreboard players set @s[scores={ranged_level=26}] ranged_xp_r 2461
scoreboard players set @s[scores={ranged_level=27}] ranged_xp_r 2656
scoreboard players set @s[scores={ranged_level=28}] ranged_xp_r 2864
scoreboard players set @s[scores={ranged_level=29}] ranged_xp_r 3086
scoreboard players set @s[scores={ranged_level=30}] ranged_xp_r 3323
scoreboard players set @s[scores={ranged_level=31}] ranged_xp_r 3575
scoreboard players set @s[scores={ranged_level=32}] ranged_xp_r 3843
scoreboard players set @s[scores={ranged_level=33}] ranged_xp_r 4128
scoreboard players set @s[scores={ranged_level=34}] ranged_xp_r 4429
scoreboard players set @s[scores={ranged_level=35}] ranged_xp_r 4747
scoreboard players set @s[scores={ranged_level=36}] ranged_xp_r 5083
scoreboard players set @s[scores={ranged_level=37}] ranged_xp_r 5438
scoreboard players set @s[scores={ranged_level=38}] ranged_xp_r 5812
scoreboard players set @s[scores={ranged_level=39}] ranged_xp_r 6205
scoreboard players set @s[scores={ranged_level=40}] ranged_xp_r 6617
scoreboard players set @s[scores={ranged_level=41}] ranged_xp_r 7051
scoreboard players set @s[scores={ranged_level=42}] ranged_xp_r 7505
scoreboard players set @s[scores={ranged_level=43}] ranged_xp_r 7981
scoreboard players set @s[scores={ranged_level=44}] ranged_xp_r 8479
scoreboard players set @s[scores={ranged_level=45}] ranged_xp_r 9000
scoreboard players set @s[scores={ranged_level=46}] ranged_xp_r 9543
scoreboard players set @s[scores={ranged_level=47}] ranged_xp_r 10110
scoreboard players set @s[scores={ranged_level=48}] ranged_xp_r 10702
scoreboard players set @s[scores={ranged_level=49}] ranged_xp_r 11318
scoreboard players set @s[scores={ranged_level=50}] ranged_xp_r 11959
scoreboard players set @s[scores={ranged_level=51}] ranged_xp_r 12626
scoreboard players set @s[scores={ranged_level=52}] ranged_xp_r 13319
scoreboard players set @s[scores={ranged_level=53}] ranged_xp_r 14039
scoreboard players set @s[scores={ranged_level=54}] ranged_xp_r 14787
scoreboard players set @s[scores={ranged_level=55}] ranged_xp_r 15562
scoreboard players set @s[scores={ranged_level=56}] ranged_xp_r 16365
scoreboard players set @s[scores={ranged_level=57}] ranged_xp_r 17198
scoreboard players set @s[scores={ranged_level=58}] ranged_xp_r 18060
scoreboard players set @s[scores={ranged_level=59}] ranged_xp_r 18951
scoreboard players set @s[scores={ranged_level=60}] ranged_xp_r 19873
scoreboard players set @s[scores={ranged_level=61}] ranged_xp_r 20826
scoreboard players set @s[scores={ranged_level=62}] ranged_xp_r 21811
scoreboard players set @s[scores={ranged_level=63}] ranged_xp_r 22828
scoreboard players set @s[scores={ranged_level=64}] ranged_xp_r 23877
scoreboard players set @s[scores={ranged_level=65}] ranged_xp_r 24959
scoreboard players set @s[scores={ranged_level=66}] ranged_xp_r 26075
scoreboard players set @s[scores={ranged_level=67}] ranged_xp_r 27255
scoreboard players set @s[scores={ranged_level=68}] ranged_xp_r 28410
scoreboard players set @s[scores={ranged_level=69}] ranged_xp_r 29630
scoreboard players set @s[scores={ranged_level=70}] ranged_xp_r 30885
scoreboard players set @s[scores={ranged_level=71}] ranged_xp_r 32177
scoreboard players set @s[scores={ranged_level=72}] ranged_xp_r 33505
scoreboard players set @s[scores={ranged_level=73}] ranged_xp_r 34871
scoreboard players set @s[scores={ranged_level=74}] ranged_xp_r 36275
scoreboard players set @s[scores={ranged_level=75}] ranged_xp_r 37717
scoreboard players set @s[scores={ranged_level=76}] ranged_xp_r 39197
scoreboard players set @s[scores={ranged_level=77}] ranged_xp_r 40717
scoreboard players set @s[scores={ranged_level=78}] ranged_xp_r 42277
scoreboard players set @s[scores={ranged_level=79}] ranged_xp_r 43878
scoreboard players set @s[scores={ranged_level=80}] ranged_xp_r 45519
scoreboard players set @s[scores={ranged_level=81}] ranged_xp_r 47202
scoreboard players set @s[scores={ranged_level=82}] ranged_xp_r 48927
scoreboard players set @s[scores={ranged_level=83}] ranged_xp_r 50694
scoreboard players set @s[scores={ranged_level=84}] ranged_xp_r 52505
scoreboard players set @s[scores={ranged_level=85}] ranged_xp_r 54359
scoreboard players set @s[scores={ranged_level=86}] ranged_xp_r 56257
scoreboard players set @s[scores={ranged_level=87}] ranged_xp_r 58200
scoreboard players set @s[scores={ranged_level=88}] ranged_xp_r 60188
scoreboard players set @s[scores={ranged_level=89}] ranged_xp_r 62221
scoreboard players set @s[scores={ranged_level=90}] ranged_xp_r 64301
scoreboard players set @s[scores={ranged_level=91}] ranged_xp_r 66427
scoreboard players set @s[scores={ranged_level=92}] ranged_xp_r 68601
scoreboard players set @s[scores={ranged_level=93}] ranged_xp_r 70823
scoreboard players set @s[scores={ranged_level=94}] ranged_xp_r 73093
scoreboard players set @s[scores={ranged_level=95}] ranged_xp_r 75411
scoreboard players set @s[scores={ranged_level=96}] ranged_xp_r 77779
scoreboard players set @s[scores={ranged_level=97}] ranged_xp_r 80197
scoreboard players set @s[scores={ranged_level=98}] ranged_xp_r 82665
scoreboard players set @s[scores={ranged_level=99}] ranged_xp_r 85185
scoreboard players set @s[scores={ranged_level=100}] ranged_xp_r 87755
scoreboard players set @s[scores={ranged_level=101}] ranged_xp_r 90378
scoreboard players set @s[scores={ranged_level=102}] ranged_xp_r 93053
scoreboard players set @s[scores={ranged_level=103}] ranged_xp_r 95781
scoreboard players set @s[scores={ranged_level=104}] ranged_xp_r 98563
scoreboard players set @s[scores={ranged_level=105}] ranged_xp_r 101399
scoreboard players set @s[scores={ranged_level=106}] ranged_xp_r 104289
scoreboard players set @s[scores={ranged_level=107}] ranged_xp_r 107234
scoreboard players set @s[scores={ranged_level=108}] ranged_xp_r 110236
scoreboard players set @s[scores={ranged_level=109}] ranged_xp_r 113293
scoreboard players set @s[scores={ranged_level=110}] ranged_xp_r 116407
scoreboard players set @s[scores={ranged_level=111}] ranged_xp_r 119578
scoreboard players set @s[scores={ranged_level=112}] ranged_xp_r 122807
scoreboard players set @s[scores={ranged_level=113}] ranged_xp_r 126094
scoreboard players set @s[scores={ranged_level=114}] ranged_xp_r 129441
scoreboard players set @s[scores={ranged_level=115}] ranged_xp_r 132846
scoreboard players set @s[scores={ranged_level=116}] ranged_xp_r 136311
scoreboard players set @s[scores={ranged_level=117}] ranged_xp_r 139837
scoreboard players set @s[scores={ranged_level=118}] ranged_xp_r 143423
scoreboard players set @s[scores={ranged_level=119}] ranged_xp_r 147071