scoreboard players set @s[scores={thieving_level=2}] thieving_xp_r 535
scoreboard players set @s[scores={thieving_level=3}] thieving_xp_r 548
scoreboard players set @s[scores={thieving_level=4}] thieving_xp_r 573
scoreboard players set @s[scores={thieving_level=5}] thieving_xp_r 600
scoreboard players set @s[scores={thieving_level=6}] thieving_xp_r 629
scoreboard players set @s[scores={thieving_level=7}] thieving_xp_r 661
scoreboard players set @s[scores={thieving_level=8}] thieving_xp_r 696
scoreboard players set @s[scores={thieving_level=9}] thieving_xp_r 735
scoreboard players set @s[scores={thieving_level=10}] thieving_xp_r 777
scoreboard players set @s[scores={thieving_level=11}] thieving_xp_r 825
scoreboard players set @s[scores={thieving_level=12}] thieving_xp_r 878
scoreboard players set @s[scores={thieving_level=13}] thieving_xp_r 936
scoreboard players set @s[scores={thieving_level=14}] thieving_xp_r 1001
scoreboard players set @s[scores={thieving_level=15}] thieving_xp_r 1073
scoreboard players set @s[scores={thieving_level=16}] thieving_xp_r 1152
scoreboard players set @s[scores={thieving_level=17}] thieving_xp_r 1238
scoreboard players set @s[scores={thieving_level=18}] thieving_xp_r 1334
scoreboard players set @s[scores={thieving_level=19}] thieving_xp_r 1438
scoreboard players set @s[scores={thieving_level=20}] thieving_xp_r 1552
scoreboard players set @s[scores={thieving_level=21}] thieving_xp_r 1675
scoreboard players set @s[scores={thieving_level=22}] thieving_xp_r 1809
scoreboard players set @s[scores={thieving_level=23}] thieving_xp_r 1954
scoreboard players set @s[scores={thieving_level=24}] thieving_xp_r 2111
scoreboard players set @s[scores={thieving_level=25}] thieving_xp_r 2280
scoreboard players set @s[scores={thieving_level=26}] thieving_xp_r 2461
scoreboard players set @s[scores={thieving_level=27}] thieving_xp_r 2656
scoreboard players set @s[scores={thieving_level=28}] thieving_xp_r 2864
scoreboard players set @s[scores={thieving_level=29}] thieving_xp_r 3086
scoreboard players set @s[scores={thieving_level=30}] thieving_xp_r 3323
scoreboard players set @s[scores={thieving_level=31}] thieving_xp_r 3575
scoreboard players set @s[scores={thieving_level=32}] thieving_xp_r 3843
scoreboard players set @s[scores={thieving_level=33}] thieving_xp_r 4128
scoreboard players set @s[scores={thieving_level=34}] thieving_xp_r 4429
scoreboard players set @s[scores={thieving_level=35}] thieving_xp_r 4747
scoreboard players set @s[scores={thieving_level=36}] thieving_xp_r 5083
scoreboard players set @s[scores={thieving_level=37}] thieving_xp_r 5438
scoreboard players set @s[scores={thieving_level=38}] thieving_xp_r 5812
scoreboard players set @s[scores={thieving_level=39}] thieving_xp_r 6205
scoreboard players set @s[scores={thieving_level=40}] thieving_xp_r 6617
scoreboard players set @s[scores={thieving_level=41}] thieving_xp_r 7051
scoreboard players set @s[scores={thieving_level=42}] thieving_xp_r 7505
scoreboard players set @s[scores={thieving_level=43}] thieving_xp_r 7981
scoreboard players set @s[scores={thieving_level=44}] thieving_xp_r 8479
scoreboard players set @s[scores={thieving_level=45}] thieving_xp_r 9000
scoreboard players set @s[scores={thieving_level=46}] thieving_xp_r 9543
scoreboard players set @s[scores={thieving_level=47}] thieving_xp_r 10110
scoreboard players set @s[scores={thieving_level=48}] thieving_xp_r 10702
scoreboard players set @s[scores={thieving_level=49}] thieving_xp_r 11318
scoreboard players set @s[scores={thieving_level=50}] thieving_xp_r 11959
scoreboard players set @s[scores={thieving_level=51}] thieving_xp_r 12626
scoreboard players set @s[scores={thieving_level=52}] thieving_xp_r 13319
scoreboard players set @s[scores={thieving_level=53}] thieving_xp_r 14039
scoreboard players set @s[scores={thieving_level=54}] thieving_xp_r 14787
scoreboard players set @s[scores={thieving_level=55}] thieving_xp_r 15562
scoreboard players set @s[scores={thieving_level=56}] thieving_xp_r 16365
scoreboard players set @s[scores={thieving_level=57}] thieving_xp_r 17198
scoreboard players set @s[scores={thieving_level=58}] thieving_xp_r 18060
scoreboard players set @s[scores={thieving_level=59}] thieving_xp_r 18951
scoreboard players set @s[scores={thieving_level=60}] thieving_xp_r 19873
scoreboard players set @s[scores={thieving_level=61}] thieving_xp_r 20826
scoreboard players set @s[scores={thieving_level=62}] thieving_xp_r 21811
scoreboard players set @s[scores={thieving_level=63}] thieving_xp_r 22828
scoreboard players set @s[scores={thieving_level=64}] thieving_xp_r 23877
scoreboard players set @s[scores={thieving_level=65}] thieving_xp_r 24959
scoreboard players set @s[scores={thieving_level=66}] thieving_xp_r 26075
scoreboard players set @s[scores={thieving_level=67}] thieving_xp_r 27255
scoreboard players set @s[scores={thieving_level=68}] thieving_xp_r 28410
scoreboard players set @s[scores={thieving_level=69}] thieving_xp_r 29630
scoreboard players set @s[scores={thieving_level=70}] thieving_xp_r 30885
scoreboard players set @s[scores={thieving_level=71}] thieving_xp_r 32177
scoreboard players set @s[scores={thieving_level=72}] thieving_xp_r 33505
scoreboard players set @s[scores={thieving_level=73}] thieving_xp_r 34871
scoreboard players set @s[scores={thieving_level=74}] thieving_xp_r 36275
scoreboard players set @s[scores={thieving_level=75}] thieving_xp_r 37717
scoreboard players set @s[scores={thieving_level=76}] thieving_xp_r 39197
scoreboard players set @s[scores={thieving_level=77}] thieving_xp_r 40717
scoreboard players set @s[scores={thieving_level=78}] thieving_xp_r 42277
scoreboard players set @s[scores={thieving_level=79}] thieving_xp_r 43878
scoreboard players set @s[scores={thieving_level=80}] thieving_xp_r 45519
scoreboard players set @s[scores={thieving_level=81}] thieving_xp_r 47202
scoreboard players set @s[scores={thieving_level=82}] thieving_xp_r 48927
scoreboard players set @s[scores={thieving_level=83}] thieving_xp_r 50694
scoreboard players set @s[scores={thieving_level=84}] thieving_xp_r 52505
scoreboard players set @s[scores={thieving_level=85}] thieving_xp_r 54359
scoreboard players set @s[scores={thieving_level=86}] thieving_xp_r 56257
scoreboard players set @s[scores={thieving_level=87}] thieving_xp_r 58200
scoreboard players set @s[scores={thieving_level=88}] thieving_xp_r 60188
scoreboard players set @s[scores={thieving_level=89}] thieving_xp_r 62221
scoreboard players set @s[scores={thieving_level=90}] thieving_xp_r 64301
scoreboard players set @s[scores={thieving_level=91}] thieving_xp_r 66427
scoreboard players set @s[scores={thieving_level=92}] thieving_xp_r 68601
scoreboard players set @s[scores={thieving_level=93}] thieving_xp_r 70823
scoreboard players set @s[scores={thieving_level=94}] thieving_xp_r 73093
scoreboard players set @s[scores={thieving_level=95}] thieving_xp_r 75411
scoreboard players set @s[scores={thieving_level=96}] thieving_xp_r 77779
scoreboard players set @s[scores={thieving_level=97}] thieving_xp_r 80197
scoreboard players set @s[scores={thieving_level=98}] thieving_xp_r 82665
scoreboard players set @s[scores={thieving_level=99}] thieving_xp_r 85185
scoreboard players set @s[scores={thieving_level=100}] thieving_xp_r 87755
scoreboard players set @s[scores={thieving_level=101}] thieving_xp_r 90378
scoreboard players set @s[scores={thieving_level=102}] thieving_xp_r 93053
scoreboard players set @s[scores={thieving_level=103}] thieving_xp_r 95781
scoreboard players set @s[scores={thieving_level=104}] thieving_xp_r 98563
scoreboard players set @s[scores={thieving_level=105}] thieving_xp_r 101399
scoreboard players set @s[scores={thieving_level=106}] thieving_xp_r 104289
scoreboard players set @s[scores={thieving_level=107}] thieving_xp_r 107234
scoreboard players set @s[scores={thieving_level=108}] thieving_xp_r 110236
scoreboard players set @s[scores={thieving_level=109}] thieving_xp_r 113293
scoreboard players set @s[scores={thieving_level=110}] thieving_xp_r 116407
scoreboard players set @s[scores={thieving_level=111}] thieving_xp_r 119578
scoreboard players set @s[scores={thieving_level=112}] thieving_xp_r 122807
scoreboard players set @s[scores={thieving_level=113}] thieving_xp_r 126094
scoreboard players set @s[scores={thieving_level=114}] thieving_xp_r 129441
scoreboard players set @s[scores={thieving_level=115}] thieving_xp_r 132846
scoreboard players set @s[scores={thieving_level=116}] thieving_xp_r 136311
scoreboard players set @s[scores={thieving_level=117}] thieving_xp_r 139837
scoreboard players set @s[scores={thieving_level=118}] thieving_xp_r 143423
scoreboard players set @s[scores={thieving_level=119}] thieving_xp_r 147071